use_frameworks!
platform :ios, '11.0'

target 'KeyboardController_Example' do
  pod 'KeyboardController', :path => '../'

  target 'KeyboardController_Tests' do
    inherit! :search_paths


  end
end
